/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'moshafy';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ABOUT = 'assets/images/about.png';
  static const String EVENING_AZKAR = 'assets/images/evening_azkar.png';
  static const String ICAON_SAVE = 'assets/images/icaon_save.png';
  static const String ICON_SAVED = 'assets/images/icon_saved.png';
  static const String LANGAUGES = 'assets/images/langauges.png';
  static const String MORE = 'assets/images/more.png';
  static const String MORNING_AZKAR = 'assets/images/morning_azkar.png';
  static const String THEMES = 'assets/images/themes.png';
}
